apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacksimpflipynginx
  namespace: app
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: app
      labels:
        app: nginx
    spec:
      containers:
      - name: stacksimpflipynginx
        image: stacksimplify/kubenginx:1.0.0
        ports:
        - containerPort: 80
